#!/bin/bash

# Killing previous tries to read
toKill=$(ps aux | grep "ttyUSB$1" | grep "sed" | grep -v "grep" | awk '{print $2}' | tr "\n" " ")
if [ -n "$toKill" ]; then
  for myKill in $toKill;
  do
    echo "Killing: $myKill"
    kill $myKill
  done
fi

# Logging command
echo "$(date): \"$2\"" >> runAttenuator.log
echo "$(tail --lines=42 runAttenuator.log)" > runAttenuator.log

# Opening reading stream
sed '/Done/q' /dev/ttyUSB$1 &
sleep 0.05

# Sending the command
echo -e "$2" > /dev/ttyUSB$1

#
