#!/bin/bash

# Logging command
echo "$(date): \"$2\"" >> runGenerator.log
echo "$(tail --lines=420 runGenerator.log)" > runGenerator.log

# Executing the command
/snap/bin/lxi scpi -a $1 "$2" &
commandPid=$!

/var/www/html/runTimeout 1 $commandPid &

exit 0
