#!/bin/bash

# Getting the temperatures
temps=$(/var/www/html/runLaser GMTE)
if [ "$temps" == "TIMEOUT" ]; then
  exit 1
fi

temps=$(echo $temps | awk '{"date +%s"|getline tmp; printf "%d,%.2f,%.2f,%.2f,%.2f", tmp, $2/100, $3/100, $4, $5}')

# Updating temps file
echo "$temps" >> /var/www/html/runLaserTemps.csv
echo "$(tail --lines=1000 /var/www/html/runLaserTemps.csv)" > /var/www/html/runLaserTemps.csv

/var/www/html/runLaserTemps.py
